#ifndef MAIN_HPP
#define MAIN_HPP

#include "Basic.hpp"
#include "Containers.hpp"
#include "CopyMoveCtor.hpp"
#include "Exceptions.hpp"
#include "Function.hpp"
#include "IO.hpp"
#include "Literals.hpp"
#include "Macros.hpp"
#include "MyArray.hpp"
#include "MyForwardList.hpp"
#include "Networking.hpp"
#include "OverloadOperator.hpp"
#include "Pimpl.hpp"
#include "PredefinedMacros.hpp"
#include "Promise.hpp"
#include "Runnable.hpp"
#include "SmartPointer.hpp"
#include "Str.hpp"
#include "SyncQueue.hpp"
#include "Tricks.hpp"
#include "UID.hpp"
#include "UsingVsTypedef.hpp"
#include "VectorVsList.hpp"
#include "WeakPointer.hpp"
#include "clsA.hpp"
#include "functor.hpp"
#include "initialyzerlist.hpp"
#include "manipulators.hpp"
#include "virtualdestructor.hpp"

#endif
